name: TraveLight
services:
  postgresql:
    image: postgres:16
    container_name: beehive-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: TraveLight
      POSTGRES_PASSWORD: TraveLight
      POSTGRES_DB: TraveLight
      TZ: Asia/Shanghai
      PGTZ: Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U TraveLight -d TraveLight"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - beehive-network

  redis:
    image: redis:8-alpine
    container_name: beehive-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ../../data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - beehive-network

networks:
  beehive-network:
    driver: bridge
