// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/crawl/start": {
            "post": {
                "description": "启动景点数据爬虫任务，异步执行",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "crawl"
                ],
                "summary": "启动爬虫任务",
                "responses": {
                    "200": {
                        "description": "爬虫任务已启动",
                        "schema": {
                            "$ref": "#/definitions/v1.StartCrawlResponse"
                        }
                    },
                    "409": {
                        "description": "爬虫正在运行中",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/crawl/status": {
            "get": {
                "description": "获取当前爬虫任务的运行状态和上次执行结果",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "crawl"
                ],
                "summary": "获取爬虫状态",
                "responses": {
                    "200": {
                        "description": "获取状态成功",
                        "schema": {
                            "$ref": "#/definitions/v1.StatusCrawlResponse"
                        }
                    }
                }
            }
        },
        "/livez": {
            "get": {
                "description": "检查服务是否存活",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "livez",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "检查服务是否就绪",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "就绪检查",
                "responses": {
                    "200": {
                        "description": "readyz",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.StartCrawlResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "v1.StatusCrawlResponse": {
            "type": "object",
            "properties": {
                "is_running": {
                    "type": "boolean"
                },
                "last_count": {
                    "type": "integer"
                },
                "last_error": {
                    "type": "string"
                },
                "last_run": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
